services:
  db:
    image: 'postgres:${DB_IMAGE_TAG}'
    container_name: db
    environment:
      - 'POSTGRES_DB=radiostation_db'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASS}'
    ports:
      - '5432:5432'
