server:
  port: 9999
  servlet:
    context-path: /radiostation

spring:
  main:
    allow-circular-references: true # added to support circular injection of mapstruct's mapper,
    #  do not use it for regular service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/radiostation_db?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa.open-in-view: false
logging.level.org.springframework.web.filter:
  CommonsRequestLoggingFilter: DEBUG
